["protocol supported"]
description = "{protocol}-Protokoll unterstützt"

["dialect supported"]
description = "{protocol}: Dialekt unterstützt: {dialect}"

["signing r:True"]
description = "{protocol}: Signatur erforderlich"

["signing r:False"]
description = "{protocol}: Signatur nicht erforderlich"

["improper access control: anonymous"]
description = "unsichere Zugriffskontrolle: Null-Session"

["improper access control: non-existing user"]
description = "unsichere Zugriffskontrolle: nichtexistierender Benutzer"

["improper access control"]
description = "unsichere Zugriffskontrolle: {authentication}"

["info leak"]
description = "Klartextspeicherung sensibler Informationen: `{info}`"

["additional info"]
description = "zusätzliche Informationen: {info}"
