["protocol supported"]
description = "{protocol}: Protokoll unterstützt"

["dialect supported"]
description = "{protocol}: Dialekt unterstützt: {dialect}"
references = [
  "[Manage SMB dialects](https://learn.microsoft.com/de-de/windows-server/storage/file-server/manage-smb-dialects)"
]

["protocol not supported"]
description = "{protocol}: Protokoll nicht unterstützt"

["dialect not supported"]
description = "{protocol}: Dialekt nicht unterstützt: {dialect}"
references = [
  "[Manage SMB dialects](https://learn.microsoft.com/de-de/windows-server/storage/file-server/manage-smb-dialects)"
]

["signing r:True"]
description = "{protocol}: Signatur erforderlich"

["signing r:False"]
description = "{protocol}: Signatur nicht erforderlich"
references = [
  "[What is Server Message Block signing?](https://learn.microsoft.com/de-de/windows-server/storage/file-server/smb-signing-overview)"
]

["authentication: anonymous"]
description = "anonymer Zugriff (Null-Session) erlaubt"

["authentication: guest"]
description = "Gast-Zugriff erlaubt"
references = [
  "[AllowInsecureGuestAuth](https://learn.microsoft.com/de-de/windows-hardware/customize/desktop/unattend/microsoft-windows-workstationservice-allowinsecureguestauth)",
  "[smb.conf - map to guest](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#MAPTOGUEST)"
]

["authentication"]
description = "Authentifizierung mittels {authentication} erlaubt"

["info leak"]
description = "Klartextspeicherung sensibler Informationen: `{info}`"

["additional info"]
description = "zusätzliche Informationen: {info}"
