["protocol supported"]
description = "{protocol}-Protokoll unterstützt"

["dialect supported"]
description = "{protocol}: Dialekt unterstützt: {dialect}"

["signing"]
description = "{protocol}: Signatur aktiviert/erforderlich: {enabled}/{required}"
