["protocol supported"]
description = "{protocol}-Protokoll unterstützt"

["dialect supported"]
description = "{protocol}: Dialekt unterstützt: {dialect}"

["signing r:True"]
description = "{protocol}: Signatur erforderlich"

["signing r:False"]
description = "{protocol}: Signatur nicht erforderlich"

["null session allowed"]
description = "Null-Session erlaubt"

["anonymous access"]
description = "anonymer Zugriff erlaubt"

["info leak"]
description = "Klartextspeicherung sensibler Informationen: `{info}`"

["additional info"]
description = "zusätzliche Informationen: {info}"
