["protocol supported"]
description = "{protocol}: Protokoll unterstützt"
recommendations = [
  "[deaktivieren Sie {protocol} in Windows](https://learn.microsoft.com/de-de/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)"
]

["dialect supported"]
description = "{protocol}: Dialekt unterstützt: {dialect}"
recommendations = [
  "[verwalten Sie SMB-Dialekte in Windows](https://learn.microsoft.com/de-de/windows-server/storage/file-server/manage-smb-dialects)"
]

["protocol not supported"]
description = "{protocol}: Protokoll nicht unterstützt"
recommendations = [
  "[aktivieren Sie {protocol} in Windows](https://learn.microsoft.com/de-de/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)"
]

["dialect not supported"]
description = "{protocol}: Dialekt nicht unterstützt: {dialect}"
recommendations = [
  "[verwalten Sie SMB-Dialekte in Windows](https://learn.microsoft.com/de-de/windows-server/storage/file-server/manage-smb-dialects)"
]

["signing r:True"]
description = "{protocol}: Signatur erforderlich"

["signing r:False"]
description = "{protocol}: Signatur nicht erforderlich"
recommendations = [
  "[aktivieren Sie SMB-Signatur in Windows](https://learn.microsoft.com/de-de/windows-server/storage/file-server/smb-signing-overview)"
]

["authentication"]
description = "Authentifizierung mittels {method}"

["authentication: NTLM"]
description = "Authentifizierung mittels NTLM"
recommendations = [
  "[deaktivieren Sie die Verwendung von NTLM-Authentikation](https://learn.microsoft.com/de-de/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd560653(v=ws.10))"
]

["authentication: NTLM: anonymous"]
description = "NTLM: anonymer Zugriff (Null-Session) erlaubt"
recommendations = [
  "[unterbinden Sie anonymer Zugriff (Null-Session)](https://learn.microsoft.com/de-de/troubleshoot/windows-server/networking/inter-process-communication-share-null-session)"
]

["authentication: NTLM: guest"]
description = "NTLM: Gast-Zugriff erlaubt"
recommendations = [
  "[deaktivieren Sie Gast-Zugriff in Windows](https://learn.microsoft.com/de-de/windows-hardware/customize/desktop/unattend/microsoft-windows-workstationservice-allowinsecureguestauth)",
  "[deaktivieren Sie Gast-Zugriff in Samba](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#MAPTOGUEST)"
]

["AD: users: sensitive information"]
description = "Domäne: Benutzer: sensible Informationen gefunden: {users}"

["AD: users: AC"]
description = "Domäne: Benutzer: Kontoeigenschaft `{name}`: {users}"

["AD: users: AC: missing"]
description = "Domäne: Benutzer: Kontoeigenschaft `{name}` fehlt: {users}"

["AD: domain: force_logoff"]
description = "Domäne: Abmelderichtlinie: inaktive Sitzungen werden nach {value} (Tage:Stunden:Minuten:Sekunden) beendet"

["AD: domain: lockout_duration"]
description = "Domäne: Kontosperr-Richtlinie: Sperrdauer: {value} (Tage:Stunden:Minuten:Sekunden)"

["AD: domain: lockout_observation_window"]
description = "Domäne: Kontosperr-Richtlinie: Zähler wird nach {value} (Tage:Stunden:Minuten:Sekunden) zurückgesetzt"

["AD: domain: lockout_threshold"]
description = "Domäne: Kontosperr-Richtlinie: Sperrschwellwert: {value}"

["AD: domain: max_password_age"]
description = "Domäne: Passwortrichtlinie: maximales Passwortalter: {value} (Tage:Stunden:Minuten:Sekunden)"

["AD: domain: min_password_age"]
description = "Domäne: Passwortrichtlinie: minimales Passwortalter: {value} (Tage:Stunden:Minuten:Sekunden)"

["AD: domain: min_password_length"]
description = "Domäne: Passwortrichtlinie: minimale Passwortlänge: {value}"

["AD: domain: password_history_length"]
description = "Domäne: Passwortrichtlinie: Passwortverlauf: {value} Einträge"

["AD: domain: password_properties: complex: False"]
description = "Domäne: Passwortrichtlinie: Passwortkomplexität nicht erfordert"

["AD: domain: password_properties: complex: True"]
description = "Domäne: Passwortrichtlinie: Passwortkomplexität erfordert"

["AD: domain: password_properties: store_cleartext: True"]
description = "Domäne: Passwortrichtlinie: Passwörter mittels reversibler Verschlüsselung gespeichert"

["additional info"]
description = "zusätzliche Informationen: {info}"
