["protocol supported"]
description = "{protocol}: Protokoll unterstützt"

["dialect supported"]
description = "{protocol}: Dialekt unterstützt: {dialect}"

["protocol not supported"]
description = "{protocol}: Protokoll nicht unterstützt"

["dialect not supported"]
description = "{protocol}: Dialekt nicht unterstützt: {dialect}"

["signing r:True"]
description = "{protocol}: Signatur erforderlich"

["signing r:False"]
description = "{protocol}: Signatur nicht erforderlich"

["improper access control: anonymous"]
description = "unsichere Zugriffskontrolle: Null-Session"

["improper access control: guest"]
description = "unsichere Zugriffskontrolle: Gast-Benutzer"

["improper access control"]
description = "unsichere Zugriffskontrolle: {authentication}"

["info leak"]
description = "Klartextspeicherung sensibler Informationen: `{info}`"

["additional info"]
description = "zusätzliche Informationen: {info}"
