["protocol supported"]
description = "{protocol}-Protokoll unterstützt"

["dialect supported"]
description = "{protocol}: Dialekt unterstützt: {dialect}"

["signing (e:True) (r:True)"]
description = "{protocol}: Signatur aktiviert und erforderlich"

["signing (e:True) (r:False)"]
description = "{protocol}: Signatur aktiviert aber nicht erforderlich"

["signing (e:False) (r:False)"]
description = "{protocol}: Signatur nicht aktiviert und nicht erforderlich"

["signing (e:False) (r:True)"]
description = "{protocol}: Signatur nicht aktiviert aber erforderlich"

["additional info"]
description = "zusätzliche Informationen: {info}"
