["protocol supported"]
description = "{protocol}: Protokoll unterstützt"
references = [
  "[Erkennen, Aktivieren und Deaktivieren von SMBv1, SMBv2 und SMBv3 in Windows](https://learn.microsoft.com/de-de/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)"
]

["dialect supported"]
description = "{protocol}: Dialekt unterstützt: {dialect}"
references = [
  "[Verwalten von SMB-Dialekten](https://learn.microsoft.com/de-de/windows-server/storage/file-server/manage-smb-dialects)"
]

["protocol not supported"]
description = "{protocol}: Protokoll nicht unterstützt"
references = [
  "[Erkennen, Aktivieren und Deaktivieren von SMBv1, SMBv2 und SMBv3 in Windows](https://learn.microsoft.com/de-de/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)"
]

["dialect not supported"]
description = "{protocol}: Dialekt nicht unterstützt: {dialect}"
references = [
  "[Verwalten von SMB-Dialekten](https://learn.microsoft.com/de-de/windows-server/storage/file-server/manage-smb-dialects)"
]

["signing r:True"]
description = "{protocol}: Signatur erforderlich"

["signing r:False"]
description = "{protocol}: Signatur nicht erforderlich"
references = [
  "[Was sind Server Message Block-Signaturen?](https://learn.microsoft.com/de-de/windows-server/storage/file-server/smb-signing-overview)"
]

["authentication"]
description = "Authentifizierung mittels {method}"

["authentication: NTLM"]
description = "Authentifizierung mittels NTLM"
references = [
  "[Introducing the Restriction of NTLM Authentication](https://learn.microsoft.com/de-de/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd560653(v=ws.10))"
]

["authentication: NTLM: anonymous"]
description = "NTLM: anonymer Zugriff (Null-Session) erlaubt"
references = [
  "[IPC$-Freigabe- und NULL-Sitzungsverhalten in Windows](https://learn.microsoft.com/de-de/troubleshoot/windows-server/networking/inter-process-communication-share-null-session)"
]

["authentication: NTLM: guest"]
description = "NTLM: Gast-Zugriff erlaubt"
references = [
  "[AllowInsecureGuestAuth](https://learn.microsoft.com/de-de/windows-hardware/customize/desktop/unattend/microsoft-windows-workstationservice-allowinsecureguestauth)",
  "[smb.conf - map to guest](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#MAPTOGUEST)"
]

["info leak"]
description = "Klartextspeicherung sensibler Informationen: `{info}`"

["password_policy: history_count"]
description = "AD-Passwortrichtlinie: Passwortverlauf: {value} Einträge"

["password_policy: max_age"]
description = "AD-Passwortrichtlinie: maximales Passwortalter: {value}"

["password_policy: min_age"]
description = "AD-Passwortrichtlinie: minimales Passwortalter: {value}"

["password_policy: min_length"]
description = "AD-Passwortrichtlinie: minimale Passwortlänge: {value}"

["password_policy: complexity_required"]
description = "AD-Passwortrichtlinie: Passwortkomplexität erfordert: {value}"

["password_policy: reversible_encryption"]
description = "AD-Passwortrichtlinie: Passwörter mittels reversibler Verschlüsselung gespeichert: {value}"

["account_lockout_policy: threshold"]
description = "AD-Kontosperr-Richtlinie: Schwellwert: {value}"

["account_lockout_policy: duration"]
description = "AD-Kontosperr-Richtlinie: Dauer: {value} Minuten"

["account_lockout_policy: reset_counter_after"]
description = "AD-Kontosperr-Richtlinie: Zähler wird nach {value} Minuten zurückgesetzt"

["additional info"]
description = "zusätzliche Informationen: {info}"
