["protocol supported"]
description = "{protocol} protocol supported"

["dialect supported"]
description = "{protocol}: dialect supported: {dialect}"

["signing"]
description = "{protocol}: signing enabled/required: {enabled}/{required}"
