["protocol supported"]
description = "{protocol}: protocol supported"
references = [
  "[Detect, enable, and disable SMBv1, SMBv2, and SMBv3 in Windows](https://learn.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)"
]

["dialect supported"]
description = "{protocol}: dialect supported: {dialect}"
references = [
  "[Manage SMB dialects](https://learn.microsoft.com/en-us/windows-server/storage/file-server/manage-smb-dialects)"
]

["protocol not supported"]
description = "{protocol}: not supported"
references = [
  "[Detect, enable, and disable SMBv1, SMBv2, and SMBv3 in Windows](https://learn.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)"
]

["dialect not supported"]
description = "{protocol}: dialect not supported: {dialect}"
references = [
  "[Manage SMB dialects](https://learn.microsoft.com/en-us/windows-server/storage/file-server/manage-smb-dialects)"
]

["signing r:True"]
description = "{protocol}: signing required"

["signing r:False"]
description = "{protocol}: signing not required"
references = [
  "[What is Server Message Block signing?](https://learn.microsoft.com/en-us/windows-server/storage/file-server/smb-signing-overview)"
]

["authentication"]
description = "authentication via {method}"

["authentication: NTLM"]
description = "authentication via NTLM"
references = [
  "[Introducing the Restriction of NTLM Authentication](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd560653(v=ws.10))"
]

["authentication: NTLM: anonymous"]
description = "NTLM: anonymous access (null session) allowed"

["authentication: NTLM: guest"]
description = "NTLM: guest access allowed"
references = [
  "[AllowInsecureGuestAuth](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-workstationservice-allowinsecureguestauth)",
  "[smb.conf - map to guest](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#MAPTOGUEST)"
]

["info leak"]
description = "cleartext storage of sensitive information: `{info}`"

["additional info"]
description = "additional information: {info}"
