["protocol supported"]
description = "{protocol} protocol supported"

["dialect supported"]
description = "{protocol}: dialect supported: {dialect}"

["signing r:True"]
description = "{protocol}: signing required"

["signing r:False"]
description = "{protocol}: signing not required"

["null session allowed"]
description = "null session allowed"

["anonymous access"]
description = "anonymous access allowed"

["info leak"]
description = "cleartext storage of sensitive information: `{info}`"

["additional info"]
description = "additional information: {info}"
