["protocol supported"]
description = "{protocol}: protocol supported"
references = [
  "[Detect, enable, and disable SMBv1, SMBv2, and SMBv3 in Windows](https://learn.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)"
]

["dialect supported"]
description = "{protocol}: dialect supported: {dialect}"
references = [
  "[Manage SMB dialects](https://learn.microsoft.com/en-us/windows-server/storage/file-server/manage-smb-dialects)"
]

["protocol not supported"]
description = "{protocol}: not supported"
references = [
  "[Detect, enable, and disable SMBv1, SMBv2, and SMBv3 in Windows](https://learn.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)"
]

["dialect not supported"]
description = "{protocol}: dialect not supported: {dialect}"
references = [
  "[Manage SMB dialects](https://learn.microsoft.com/en-us/windows-server/storage/file-server/manage-smb-dialects)"
]

["signing r:True"]
description = "{protocol}: signing required"

["signing r:False"]
description = "{protocol}: signing not required"
references = [
  "[What is Server Message Block signing?](https://learn.microsoft.com/en-us/windows-server/storage/file-server/smb-signing-overview)"
]

["authentication"]
description = "authentication via {method}"

["authentication: NTLM"]
description = "authentication via NTLM"
references = [
  "[Introducing the Restriction of NTLM Authentication](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd560653(v=ws.10))"
]

["authentication: NTLM: anonymous"]
description = "NTLM: anonymous access (null session) allowed"
references = [
  "[IPC$ share and null session behavior in Windows](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/inter-process-communication-share-null-session)"
]

["authentication: NTLM: guest"]
description = "NTLM: guest access allowed"
references = [
  "[AllowInsecureGuestAuth](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-workstationservice-allowinsecureguestauth)",
  "[smb.conf - map to guest](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#MAPTOGUEST)"
]

["info leak"]
description = "cleartext storage of sensitive information: `{info}`"

["password_policy: history_count"]
description = "AD password policy: password history count: {value}"

["password_policy: max_age"]
description = "AD password policy: maximum password age: {value}"

["password_policy: min_age"]
description = "AD password policy: minimum password age: {value}"

["password_policy: min_length"]
description = "AD password policy: minimum password length: {value}"

["password_policy: complexity_required"]
description = "AD password policy: require complex passwords: {value}"

["password_policy: reversible_encryption"]
description = "AD password policy: store passwords using reversible encryption: {value}"

["account_lockout_policy: threshold"]
description = "AD account lockout policy: threshold: {value}"

["account_lockout_policy: duration"]
description = "AD account lockout policy: duration: {value} minutes"

["account_lockout_policy: reset_counter_after"]
description = "AD account lockout policy: reset counter after {value} minutes"

["additional info"]
description = "additional information: {info}"
