["protocol supported"]
description = "{protocol}: protocol supported"
references = [
  "[Detect, enable, and disable SMBv1, SMBv2, and SMBv3 in Windows](https://learn.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)"
]

["dialect supported"]
description = "{protocol}: dialect supported: {dialect}"
references = [
  "[Manage SMB dialects](https://learn.microsoft.com/en-us/windows-server/storage/file-server/manage-smb-dialects)"
]

["protocol not supported"]
description = "{protocol}: not supported"
references = [
  "[Detect, enable, and disable SMBv1, SMBv2, and SMBv3 in Windows](https://learn.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)"
]

["dialect not supported"]
description = "{protocol}: dialect not supported: {dialect}"
references = [
  "[Manage SMB dialects](https://learn.microsoft.com/en-us/windows-server/storage/file-server/manage-smb-dialects)"
]

["signing r:True"]
description = "{protocol}: signing required"

["signing r:False"]
description = "{protocol}: signing not required"
references = [
  "[What is Server Message Block signing?](https://learn.microsoft.com/en-us/windows-server/storage/file-server/smb-signing-overview)"
]

["authentication"]
description = "authentication via {method}"

["authentication: NTLM"]
description = "authentication via NTLM"
references = [
  "[Introducing the Restriction of NTLM Authentication](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd560653(v=ws.10))"
]

["authentication: NTLM: anonymous"]
description = "NTLM: anonymous access (null session) allowed"
references = [
  "[IPC$ share and null session behavior in Windows](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/inter-process-communication-share-null-session)"
]

["authentication: NTLM: guest"]
description = "NTLM: guest access allowed"
references = [
  "[AllowInsecureGuestAuth](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-workstationservice-allowinsecureguestauth)",
  "[smb.conf - map to guest](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#MAPTOGUEST)"
]

["AD: users: sensitive information"]
description = "domain: users: sensitive information found: {users}"

["AD: users: AC: neg"]
description = "domain: users: account control `{name}`: {users}"

["AD: users: AC: pos"]
description = "domain: users: account control `{name}` missing: {users}"

["AD: domain: force_logoff"]
description = "domain: logoff policy: inactive session timeout: {value} (days:hours:minutes:seconds)"

["AD: domain: lockout_duration"]
description = "domain: account lockout policy: lockout duration: {value} (days:hours:minutes:seconds)"

["AD: domain: lockout_observation_window"]
description = "domain: account lockout policy: reset lockout counter after {value} (days:hours:minutes:seconds)"

["AD: domain: lockout_threshold"]
description = "domain: account lockout policy: lockout threshold: {value}"

["AD: domain: max_password_age"]
description = "domain: password policy: maximum password age: {value} (days:hours:minutes:seconds)"

["AD: domain: min_password_age"]
description = "domain: password policy: minimum password age: {value} (days:hours:minutes:seconds)"

["AD: domain: min_password_length"]
description = "domain: password policy: minimum password length: {value}"

["AD: domain: password_history_length"]
description = "domain: password policy: password history count: {value}"

["AD: domain: password_properties: complex: False"]
description = "domain: password policy: does not require complex passwords"

["AD: domain: password_properties: complex: True"]
description = "domain: password policy: requires complex passwords"

["AD: domain: password_properties: store_cleartext: True"]
description = "domain: password policy: store passwords using reversible encryption"

["additional info"]
description = "additional information: {info}"
