["protocol supported"]
description = "{protocol}: protocol supported"

["dialect supported"]
description = "{protocol}: dialect supported: {dialect}"
references = [
  "[Manage SMB dialects](https://learn.microsoft.com/en-us/windows-server/storage/file-server/manage-smb-dialects)"
]

["protocol not supported"]
description = "{protocol}: not supported"

["dialect not supported"]
description = "{protocol}: dialect not supported: {dialect}"
references = [
  "[Manage SMB dialects](https://learn.microsoft.com/en-us/windows-server/storage/file-server/manage-smb-dialects)"
]

["signing r:True"]
description = "{protocol}: signing required"

["signing r:False"]
description = "{protocol}: signing not required"
references = [
  "[What is Server Message Block signing?](https://learn.microsoft.com/en-us/windows-server/storage/file-server/smb-signing-overview)"
]

["authentication: anonymous"]
description = "anonymous access (null session) allowed"

["authentication: guest"]
description = "guest access allowed"
references = [
  "[AllowInsecureGuestAuth](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-workstationservice-allowinsecureguestauth)",
  "[smb.conf - map to guest](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#MAPTOGUEST)"
]

["authentication"]
description = "authentication via {authentication} allowed"

["info leak"]
description = "cleartext storage of sensitive information: `{info}`"

["additional info"]
description = "additional information: {info}"
