["protocol supported"]
description = "{protocol}: protocol supported"

["dialect supported"]
description = "{protocol}: dialect supported: {dialect}"

["protocol not supported"]
description = "{protocol}: not supported"

["dialect not supported"]
description = "{protocol}: dialect not supported: {dialect}"

["signing r:True"]
description = "{protocol}: signing required"

["signing r:False"]
description = "{protocol}: signing not required"

["improper access control: anonymous"]
description = "improper access control: null session"

["improper access control: non-existing user"]
description = "improper access control: non-existing user"

["improper access control"]
description = "improper access control: {authentication}"

["info leak"]
description = "cleartext storage of sensitive information: `{info}`"

["additional info"]
description = "additional information: {info}"
