["SMB dialect supported"]
description = "SMB Dialect supported: {version}"

["SMBv1 signing disabled"]
description = "SMBv1/CIFS signing is {state} and {}"

["SMB signing incorrect"]
description = "SMB singing: {issue}"

["Netbios enabled"]
description = "Netbios is enabled"

["Netbios Info"]
description = "Possible information disclosure through Netbios {info}"

["Signing optional"]
description = "{proto}: Message signing enabled but not required"

["Singning disabled but required"]
description = "{proto}: Message signing is disabled and not required!"

["Singing disabled"]
description = "{proto}: Message signing is disabled!"