["public DNS server"]
description = "öffentlicher DNS-Server"

["recursive DNS"]
description = "unterstützt rekursive Namensauflösung (\"recursive DNS\"): dies könnte für sogenannte \"Traffic Amplification\"-Angriffe missbraucht werden"
references = [
  "[Cloudflare: What is recursive DNS?](https://www.cloudflare.com/learning/dns/what-is-recursive-dns/)",
]

["DNSSEC not validated"]
description = "validiert kein DNSSEC: dies könnte zu DNS-Cache-Poisoning führen"

["ECS: supported"]
description = "unterstützt ECS: dies könnte die Privatsphäre der Nutzer\\*innen beeinträchtigen und gezielte DNS-Poisoning-Angriffe ermöglichen"
references = [
  "[Understanding the Privacy Implications of ECS](https://yacin.nadji.us/docs/pubs/dimva16_ecs.pdf)",
]

["ECS: not supported"]
description = "unterstützt ECS nicht: dies könnte den Lastausgleich (\"load balancing\") behindern"

["AXFR"]
description = "erlaubt AXFR: dies könnte potenziell sensible Informationen preisgeben"

["additional info"]
description = "zusätzliche Informationen: {info}"
recommendations = [
  "[deaktivieren Sie \"version reporting\"](https://kb.isc.org/docs/aa-00359)"
]
