protocol_versions = [ "TLS 1.3" ]

[certificate]
elliptic_curves = [ "prime256v1", "secp384r1" ]
signature_algorithms = [
  "ecdsa-with-SHA256",
  "ecdsa-with-SHA384",
  "ecdsa-with-SHA515"
]
lifespan = 90

  [certificate.minimum_key_length]
  ECDSA = 250

[cipher_suite]
elliptic_curves = [ "X25519", "prime256v1", "secp384r1" ]
names = [
  "TLS_AES_128_GCM_SHA256",
  "TLS_AES_256_GCM_SHA384",
  "TLS_CHACHA20_POLY1305_SHA256"
]
preference = "client"

  [cipher_suite.minimum_key_length]
  ECDH = 250

[extensions]
yes = [
  "renegotiation_info",
  "server_name",
  "extended_master_secret",
  "signature_algorithms_cert",
  "status_request"
]
no = [
  "truncated_hmac",
  "heartbeat",
  "client_certificate_url",
  "early_data"
]
