protocol_versions = [ "TLS 1.3" ]

preference = "client"

cipher_suites = [
  "TLS_AES_128_GCM_SHA256",
  "TLS_AES_256_GCM_SHA384",
  "TLS_CHACHA20_POLY1305_SHA256"
]

[key_exchange]
methods = { ECDH = 250 }
groups = [ "x25519", "prime256v1", "secp384r1" ]

[extensions]

yes = [
  "renegotiation_info",
  "server_name",
  "extended_master_secret",
  "signature_algorithms_cert",
  "status_request"
]
no = [
  "truncated_hmac",
  "heartbeat",
  "client_certificate_url",
  "early_data"
]

[certificate]

signature_algorithms = [
  "ecdsa-with-SHA256",
  "ecdsa-with-SHA384",
  "ecdsa-with-SHA515"
]

lifespan = 90

  [certificate.public_key]
  types = { ECDSA = 250 }
  curves = [ "prime256v1", "secp384r1" ]
