protocol_versions = [ "TLS 1.2", "TLS 1.3" ]

preference = "client"

cipher_suites = [
  "TLS_AES_128_GCM_SHA256",
  "TLS_AES_256_GCM_SHA384",
  "TLS_CHACHA20_POLY1305_SHA256",
  "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
  "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
  "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
  "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"
]

[key_exchange]
methods = { DH = 2000, ECDH = 250 }
groups = [ "x25519", "prime256v1", "secp384r1", "ffdhe2048" ]

[extensions]
yes = [
  "status_request"
]

[certificate]

signature_algorithms = [
  "sha256WithRSAEncryption",
  "ecdsa-with-SHA256",
  "ecdsa-with-SHA384",
  "ecdsa-with-SHA515"
]

lifespan = 366

  [certificate.public_key]
  types = { RSA = 2000, ECDSA = 250 }
  curves = [ "prime256v1", "secp384r1" ]
