# Microsoft SMB security hardening
# https://learn.microsoft.com/en-us/windows-server/storage/file-server/smb-security-hardening

# NIST password recommendations
# # https://pages.nist.gov/800-63-4/sp800-63b.html

# CIS password recommendations
# https://learn.cisecurity.org/cis-password-policy-guide-passphrases-monitoring-and-more

# allowed authentication methods
authentication_methods = [ 'Kerberos' ]
# possible values: 'Kerberos', 'NTLM'

# applications are generally advised not to use NTLM.
# https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/1e846608-4c5f-41f4-8454-1b91af8a755b

[dialect]
# minimum protocol and dialect the server must support
SMB2 = '3.1.1'

[signing]
# if a protocol (e.g. CIFS, SMB2) is not specified here, the server's configuration regarding signing is interpreted as "incorrect"/"invalid"/"insecure"

# SMB2 signing is controlled solely by being required or not.
# https://techcommunity.microsoft.com/blog/filecab/configure-smb-signing-with-confidence/2418102
SMB2 = {required = true}

[AD.users]

# regular expression to look for secrets in the information stored with a user
secrets = '(?i)password|secret|passwort|geheim|zugangsdaten'

# account control bits that should not be set
# https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-samr/b10cfda1-f24f-441b-8f43-80cb93e786ec
[AD.users.AC_bits_neg]
0x00000004 = 'PASSWORD_NOT_REQUIRED'
0x00000200 = 'DONT_EXPIRE_PASSWORD'
0x00000800 = 'ENCRYPTED_TEXT_PASSWORD_ALLOWED'
0x00008000 = 'USE_DES_KEY_ONLY'
0x00010000 = 'DONT_REQUIRE_PREAUTH'
0x00040000 = 'TRUSTED_TO_AUTHENTICATE_FOR_DELEGATION'
0x00080000 = 'NO_AUTH_DATA_REQUIRED'

# account control bits that should be set
[AD.users.AC_bits_pos]

[AD.domain]
# AD domain information, queried via SAM-R protocol
# https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-samr/d275ab19-10b0-40e0-94bb-45b7fc130025

# amount of time (in seconds) that an interactive logon session is allowed to continue
force_logoff = 900 # 15 minutes

# ACCOUNT LOCKOUT POLICY
# https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/security-policy-settings/account-lockout-policy

# duration (in seconds) for which an account is locked out before being automatically reset to an unlocked state
lockout_duration = 1800 # 30 minutes

# time period (in seconds) in which failed password attempts are counted without resetting the count to zero
lockout_observation_window = 1800 # 30 minutes

# number of bad password attempts within lockout_observation_window that will cause an account to be locked out
lockout_threshold = 5

# PASSWORD POLICY
# https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/security-policy-settings/password-policy

# maximum time (in seconds) allowed before a password reset or change is required
max_password_age = 0 # diabled

# minimum time (in seconds) allowed before a password change operation is allowed
min_password_age = 259200 # 3 days

# minimum password length
min_password_length = 15

# number of previously used passwords
password_history_length = 10

[AD.domain.password_properties]

# server enforces password complexity policy
# https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-samr/cb1f380a-0a51-4705-84cd-eea1b85953e0
complex = false

# server MUST store the cleartext password, not just the computed hashes
store_cleartext = false
