# https://learn.microsoft.com/en-us/windows-server/storage/file-server/smb-security-hardening

# allowed authentication methods
authentication_methods = [ 'Kerberos' ]
# possible values: 'Kerberos', 'NTLM'

# applications are generally advised not to use NTLM.
# https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/1e846608-4c5f-41f4-8454-1b91af8a755b

[dialect]
# minimum protocol and dialect the server must support
SMB2 = '3.1.1'

[signing]
# if a protocol (e.g. CIFS, SMB2) is not specified here, the server's configuration regarding signing is interpreted as "incorrect"/"invalid"/"insecure"

# SMB2 signing is controlled solely by being required or not.
# https://techcommunity.microsoft.com/blog/filecab/configure-smb-signing-with-confidence/2418102

SMB2 = {required = true}
