# https://learn.microsoft.com/en-us/windows-server/storage/file-server/smb-security-hardening

# allowed authentication methods
authentication_methods = [ 'Kerberos' ]
# possible values: 'Kerberos', 'NTLM'

# applications are generally advised not to use NTLM.
# https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/1e846608-4c5f-41f4-8454-1b91af8a755b

[dialect]
# minimum protocol and dialect the server must support
SMB2 = '3.1.1'

[signing]
# if a protocol (e.g. CIFS, SMB2) is not specified here, the server's configuration regarding signing is interpreted as "incorrect"/"invalid"/"insecure"

# SMB2 signing is controlled solely by being required or not.
# https://techcommunity.microsoft.com/blog/filecab/configure-smb-signing-with-confidence/2418102

SMB2 = {required = true}

[AD.password_policy]
# https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/security-policy-settings/password-policy
# https://learn.cisecurity.org/cis-password-policy-guide-passphrases-monitoring-and-more
history_count = 10 # number of passwords; prevents users from reusing previous passwords
max_age = 0 # disabled
min_age = 259200 # seconds (3*24*60*60); prevents users from rapidly changing their passwords and revert to a previously used one
min_length = 14 # number of characters
complexity_required = true # mandating a mix of character types (upper and lower case letters, numbers, and special characters)
reversible_encryption = false

[AD.account_lockout_policy]
# https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/security-policy-settings/account-lockout-policy
# https://learn.cisecurity.org/cis-password-policy-guide-passphrases-monitoring-and-more
threshold = 5 # number of failed logon attempts before an account is locked out
duration = 30 # how many minutes an account should be locked out
reset_counter_after = 30 # number of minutes that should elapse, after a failed logon attempt, for the failed logon counter to be reset to 0
