# allowed authentication methods:
# null, password, Kerberos, NTLM hash, non-existing user
authentications = [ 'password', 'Kerberos' ]

[dialect]
# minimum protocol and dialect the server must support
SMB2 = '3.1.1'

[signing]
# The "signing enabled" registry setting for SMB2+ client and SMB2+ Server is ignored.
# SMB2 signing is controlled solely by being required or not.
# https://techcommunity.microsoft.com/blog/filecab/configure-smb-signing-with-confidence/2418102

# if a protocol (e.g. SMB/CIFS) is not specified here, the server's configuration regarding signing is interpreted as "incorrect"/"invalid"/"insecure"

SMB2 = {required = true}
