# minimum dialect the server must support
[dialect]
SMB2 = '3.1.1'

# if a protocol (e.g. SMB/CIFS) is not specified here, the server's configuration regarding signing is interpreted as "incorrect"/"invalid"/"insecure"
[signing]
SMB2 = {enabled = true, required = true}
