["public FTP server"]
description = "öffentlicher FTP-Server"

["no FTPS"]
description = "unterstützt kein FTPS"

["anonymous access"]
description = "erlaubt anonymen Zugang"
recommendations = [ "erlaubt Sie keinen anonymen Zugang" ]

["bouncing"]
description = "Server erlaubt \"Bouncing\""

["bouncing: no low ports"]
description = "Server verbietet \"Bouncing\" zu niedrigen Ports <1025"

["ProFTPD backdoor"]
description = "auf dem Server scheint eine Version von ProFTPd zu laufen, die eine Hintertür enthält (Version `1.3.3c`)"
recommendations = [ "aktualisieren Sie die FTP-Software" ]
references = [
  "[Exploit DB: ProFTPD backdoor](https://www.exploit-db.com/exploits/15662)"
]

["vsFTPd backdoor"]
description = "auf dem Server scheint eine Version von vsFTPd zu laufen, die eine Hintertür enthält (Version `2.3.4`)"
recommendations = [ "aktualisieren Sie die FTP-Software" ]
references = [
  "[CVE-2011-2523](https://nvd.nist.gov/vuln/detail/CVE-2011-2523)"
]

["ProFTPD buffer overflow"]
description = "auf dem Server scheint eine Version von ProFTPD zu laufen, die eine Pufferüberlaufschwachstelle enthält (Versionen `1.3.2rc3` bis `1.3.3b`)"
references = [
  "[CVE-2010-4221](https://nvd.nist.gov/vuln/detail/CVE-2010-4221)"
]
