["protocol: supported"]
description = "Protokoll wird unterstützt: {deviation}"
recommendations = [ "deaktivieren Sie {deviation}" ]

["protocol: not supported"]
description = "Protokoll wird nicht unterstützt: {deviation}"
recommendations = [ "unterstützen Sie {deviation}" ]

["IKEv1: Aggressive Mode supported"]
description = "IKEv1: \"Aggressive Mode\" wird unterstützt"

["IKEv1: Aggressive Mode not supported"]
description = "IKEv1: \"Aggressive Mode\" wird nicht unterstützt"

["IKE Attributes: supported"]
description = "\"{name}\" wird unterstützt: `{deviation}`"
references = [
  "[IANA: IKE Attributes](https://www.iana.org/assignments/ipsec-registry/ipsec-registry.xhtml)",
]

["IKE Attributes: not supported"]
description = "\"{name}\" wird nicht unterstützt: `{deviation}`"

["IKEv2 Parameters: supported"]
description = "\"{name}\" wird unterstützt: `{deviation}`"
references = [
  "[IANA: IKEv2 Parameters](https://www.iana.org/assignments/ikev2-parameters/ikev2-parameters.xhtml)",
]

["IKEv2 Parameters: not supported"]
description = "\"{name}\" wird nicht unterstützt: `{deviation}`"
